### ISSUE TITLE
Files names for files < 10 are only one digit - this makes it hard to properly order these values

### ISSUE THREAD

**Issue by drewwint** [GatesLab/gimme#40]
Example: data 1-9 are all single digits (e.g., data1Betas.csv is lower than data10Betas.csv), and what ends up happening is these files are lower in the order in the output (e.g., data1Betas.csv is lower than data10Betas.csv). is it possible to add a leading 0 or number of 0's based on the number of files? (e.g., data01Betas.csv, data001Betas.csv, or data023Betas.csv) This would help keep track of the proper order of values and lining up participants with their respective behavioral data (e.g., demographic variable with the density of gimme network) as well as order inside the output csv files.  As of now, I have to write additional code to add leading 0's to order these values - and I could see a situation where someone could mistakenly line up these values incorrectly and have inaccurate analyses.

**Comment by kgates** [comment]
We wouldn't want to rename peoples' data since that can cause unintended consequences if they want to match up gimme analyses to the data files that are read in. They would no longer match. Internally, gimme matches file name rather than ordering to avoid this problem. 

What you describe sounds like good practices for naming conventions in general, as the same ordering issue could occur when sorting files in a directory on a server, for instance. 

Was there a specific output object or file where you see this being an issue?

**Comment by drewwint** [comment]
Thanks - My mistake - user error on this because a function was used that renamed the time-series files prior to entering them into GIMME. I incorrectly assumed GIMME was using some naming convention.
